/* Auto-generated ISR swap snippet */

/* Auto-generated by emit_change_function. Do not edit. */
/* Returns 1 if any field updated, else 0 */
short  ProtectPosProfilerData_T(const PosProfilerData_T* k1, const PosProfilerData_T* k2, PosProfilerData_T* k3)
{
    short changed = 0;
    if (k1->PositionTarget != k2->PositionTarget) { k3->PositionTarget = k2->PositionTarget; changed = 1; }
    if (k1->ProfileSpeed != k2->ProfileSpeed) { k3->ProfileSpeed = k2->ProfileSpeed; changed = 1; }
    if (k1->ProfileAcceleration != k2->ProfileAcceleration) { k3->ProfileAcceleration = k2->ProfileAcceleration; changed = 1; }
    if (k1->ProfileDeceleration != k2->ProfileDeceleration) { k3->ProfileDeceleration = k2->ProfileDeceleration; changed = 1; }
    for (size_t i0 = 0; i0 < 4; i0++) {
        if (k1->ProfileFilterDen[i0] != k2->ProfileFilterDen[i0]) { k3->ProfileFilterDen[i0] = k2->ProfileFilterDen[i0]; changed = 1; }
    }
    if (k1->ProfileFilterNum != k2->ProfileFilterNum) { k3->ProfileFilterNum = k2->ProfileFilterNum; changed = 1; }
    if (k1->Ts != k2->Ts) { k3->Ts = k2->Ts; changed = 1; }
    if (k1->ProfileDataOk != k2->ProfileDataOk) { k3->ProfileDataOk = k2->ProfileDataOk; changed = 1; }
    return changed;
}

/* Auto-generated by emit_change_function. Do not edit. */
/* Returns 1 if any field updated, else 0 */
short  ProtectPosProfilerState_T(const PosProfilerState_T* k1, const PosProfilerState_T* k2, PosProfilerState_T* k3)
{
    short changed = 0;
    if (k1->Position != k2->Position) { k3->Position = k2->Position; changed = 1; }
    if (k1->Speed != k2->Speed) { k3->Speed = k2->Speed; changed = 1; }
    for (size_t i0 = 0; i0 < 4; i0++) {
        if (k1->FiltState[i0] != k2->FiltState[i0]) { k3->FiltState[i0] = k2->FiltState[i0]; changed = 1; }
    }
    return changed;
}




/* Entry & Exit routines */

// Pointer definitions 
PosProfilerData_T  PosProfilerData_TRT ;
PosProfilerData_T  PosProfilerData_TBG_in ;
PosProfilerData_T  PosProfilerData_TBG_out ;
PosProfilerData_T  PosProfilerData_TBG_Backup ;



PosProfilerState_T  PosProfilerState_TRT ;
PosProfilerState_T  PosProfilerState_TBG_in ;
PosProfilerState_T  PosProfilerState_TBG_out ;
PosProfilerState_T  PosProfilerState_TBG_Backup ;



void SealPointerInit(void)
{
    Gp_PosProfilerData = &PosProfilerData_TBG_in ;
    PosProfilerData_TBG_Backup = PosProfilerData_TBG_in ;
    PosProfilerData_TBG_in = PosProfilerData_init ;
    PosProfilerData_TBG_out = PosProfilerData_init ;
    PosProfilerData_TRT = PosProfilerData_init ;

    Gp_PosProfilerState = &PosProfilerState_TBG_in ;
    PosProfilerState_TBG_Backup = PosProfilerState_TBG_in ;
    PosProfilerState_TBG_in = G_PosProfilerState_init ;
    PosProfilerState_TBG_out = G_PosProfilerState_init ;
    PosProfilerState_TRT = G_PosProfilerState_init ;

}



void PreISR(void)
{
    /* Gp_PosProfilerData : PosProfilerData_T */
    pPosProfilerData_T_Backup = Gp_PosProfilerData;
    Gp_PosProfilerData = &PosProfilerData_TRT;

    /* Gp_PosProfilerState : PosProfilerState_T */
    pPosProfilerState_T_Backup = Gp_PosProfilerState;
    Gp_PosProfilerState = &PosProfilerState_TRT;

}

void PostISR(void)
{
    /* Gp_PosProfilerData : PosProfilerData_T */
    Gp_PosProfilerData = pPosProfilerData_T_Backup;

    /* Gp_PosProfilerState : PosProfilerState_T */
    Gp_PosProfilerState = pPosProfilerState_T_Backup;

}


void PreIdle(void)
{
short unsigned mask ;
    mask = BlockInts();
    PosProfilerData_TBG_in = PosProfilerData_TRT;
    RestoreInts(mask);
    PosProfilerData_TBG_out = PosProfilerData_TBG_in;

    mask = BlockInts();
    PosProfilerState_TBG_in = PosProfilerState_TRT;
    RestoreInts(mask);
    PosProfilerState_TBG_out = PosProfilerState_TBG_in;

}



void PostIdle(void)
{
short unsigned mask ;
    mask = BlockInts();
    ProtectPosProfilerData_T( &PosProfilerData_TBG_in  ,  &PosProfilerData_TBG_out  , &PosProfilerData_TRT ); 
    RestoreInts(mask);

    mask = BlockInts();
    ProtectPosProfilerState_T( &PosProfilerState_TBG_in  ,  &PosProfilerState_TBG_out  , &PosProfilerState_TRT ); 
    RestoreInts(mask);

}
