/* Auto-generated by emit_change_function. Do not edit. */
/* Returns 1 if any field updated, else 0 */
PosProfilerState_T PosProfilerState_TBG_in ;
PosProfilerState_T PosProfilerState_TBG_out ;
PosProfilerState_T PosProfilerState_TRT ;
PosProfilerState_T *pPosProfilerState_T_Backup ;
short  ProtectPosProfilerState_T(const PosProfilerState_T* k1, const PosProfilerState_T* k2, PosProfilerState_T* k3)
{
    short changed = 0;
    if (k1->Position != k2->Position) { k3->Position = k2->Position; changed = 1; }
    if (k1->Speed != k2->Speed) { k3->Speed = k2->Speed; changed = 1; }
    for (size_t i0 = 0; i0 < 4; i0++) {
        if (k1->FiltState[i0] != k2->FiltState[i0]) { k3->FiltState[i0] = k2->FiltState[i0]; changed = 1; }
    }
    return changed;
}
